# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0022_auto_20161110_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=32140, verbose_name=b'The point'),
        ),
        migrations.AlterField(
            model_name='eventforbus',
            name='fixed',
            field=models.NullBooleanField(default=False, verbose_name=b'Fixed'),
        ),
        migrations.AlterField(
            model_name='eventforbusstop',
            name='fixed',
            field=models.NullBooleanField(default=False, verbose_name=b'Fixed'),
        ),
        migrations.AlterField(
            model_name='eventforbusstop',
            name='half_hour_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.HalfHourPeriod', verbose_name=b'Half Hour Period'),
        ),
        migrations.AlterField(
            model_name='eventforbusstop',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.TimePeriod', verbose_name=b'Time Period'),
        ),
        migrations.AlterField(
            model_name='eventforbusv2',
            name='busStop1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busStop1', to='AndroidRequests.BusStop', verbose_name=b'Bus Stop1'),
        ),
        migrations.AlterField(
            model_name='eventforbusv2',
            name='busStop2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busStop2', to='AndroidRequests.BusStop', verbose_name=b'Bus Stop2'),
        ),
        migrations.AlterField(
            model_name='eventforbusv2',
            name='fixed',
            field=models.NullBooleanField(default=False, verbose_name=b'Fixed'),
        ),
        migrations.AlterField(
            model_name='eventforbusv2',
            name='half_hour_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.HalfHourPeriod', verbose_name=b'Half Hour Period'),
        ),
        migrations.AlterField(
            model_name='eventforbusv2',
            name='time_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.TimePeriod', verbose_name=b'Time Period'),
        ),
        migrations.AlterField(
            model_name='report',
            name='imageName',
            field=models.CharField(default=b'no image', max_length=100, null=True),
        ),
    ]
