# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0024_merge_20161115_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadisticdatafromregistrationbus',
            name='distance',
            field=models.FloatField(null=True, verbose_name=b'Distance'),
        ),
        migrations.AddField(
            model_name='stadisticdatafromregistrationbus',
            name='gpsLatitud',
            field=models.FloatField(null=True, verbose_name=b'GPS Latitude'),
        ),
        migrations.AddField(
            model_name='stadisticdatafromregistrationbus',
            name='gpsLongitud',
            field=models.FloatField(null=True, verbose_name=b'GPS Longitude'),
        ),
        migrations.AddField(
            model_name='stadisticdatafromregistrationbus',
            name='gpsTimeStamp',
            field=models.DateTimeField(null=True, verbose_name=b'GPS Time Stamp'),
        ),
    ]
