# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 18:48
from __future__ import unicode_literals

from django.db import migrations

def fill_tables(apps, schema_editor):
    eventsforbusv2 = apps.get_model('AndroidRequests', 'EventForBusv2')
    eventsforbusstop = apps.get_model('AndroidRequests', 'EventForBusStop')
    busv2 = apps.get_model('AndroidRequests', 'Busv2')
    reports = apps.get_model('AndroidRequests', 'Report')
    reportsinfo = apps.get_model('AndroidRequests', 'ReportInfo')
    busesstops = apps.get_model('AndroidRequests', 'BusStop')

    for ev in eventsforbusv2.objects.all():
        ev.transformed = True
        ev.save()

    for ev in eventsforbusstop.objects.all():
        ev.transformed = True
        ev.save()

    for ev in busv2.objects.all():
        ev.transformed = True
        ev.save()

    for ev in reports.objects.all():
        ev.transformed = True
        ev.save()

    for ev in reportsinfo.objects.all():
        ev.transformed = True
        ev.save()

    for ev in busesstops.objects.all():
        ev.transformed = True
        ev.save()

class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0026_auto_20161216_2025'),
    ]

    operations = [
        migrations.RunPython(fill_tables, reverse_code=migrations.RunPython.noop),
    ]
