# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0912_transformation_20161115_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='service',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='busassignment',
            name='service',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name=b'Service'),
        ),
        migrations.AlterField(
            model_name='servicelocation',
            name='service',
            field=models.CharField(max_length=6, verbose_name=b'Service Code'),
        ),
        migrations.AlterField(
            model_name='servicesbybusstop',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='servicestopdistance',
            name='service',
            field=models.CharField(max_length=6, verbose_name=b'Service Code'),
        ),
        migrations.AlterUniqueTogether(
            name='busassignment',
            unique_together=set([]),
        ),
    ]
