# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models

def fill_tables(apps, schema_editor):

    tokentrajectory =  apps.get_model('AndroidRequests', 'PoseInTrajectoryOfToken')
    evs =  apps.get_model('AndroidRequests', 'EventForBusv2')
    reports =  apps.get_model('AndroidRequests', 'ReportInfo')

    for ev in evs.objects.all():
        direction = None
        pose = tokentrajectory.objects.filter(timeStamp__lte = ev.timeStamp, token__userId=ev.userId).order_by('-timeStamp').first()
        try:
            direction = pose.token.direction
        except:
            pass
        ev.direction = direction
        ev.save()

    for report in reports.objects.filter(reportType='bus'):
        direction = None
        pose = tokentrajectory.objects.filter(timeStamp__lte = report.report.timeStamp, token__userId=report.report.userId).order_by('-timeStamp').first()
        try:
            direction = pose.token.direction
        except:
            pass
        report.direction = direction
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0914_transformation_20161216_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventforbusv2',
            name='direction',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='direction',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.RunPython(fill_tables, reverse_code=migrations.RunPython.noop),
    ]
