# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AndroidRequests', '0916_transformation_20161219_1848'),
    ]

    operations = [

    ]
    """
    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='busstop',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='devicepositionintime',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='devicepositionintime',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='poseintrajectoryoftoken',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='poseintrajectoryoftoken',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='servicelocation',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='servicelocation',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='stadisticdatafromregistrationbus',
            old_name='gpsLatitud',
            new_name='gpsLatitude',
        ),
        migrations.RenameField(
            model_name='stadisticdatafromregistrationbus',
            old_name='gpsLongitud',
            new_name='gpsLongitude',
        ),
        migrations.RenameField(
            model_name='stadisticdatafromregistrationbus',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='stadisticdatafromregistrationbus',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='stadisticdatafromregistrationbusstop',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='stadisticdatafromregistrationbusstop',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='busstop',
            name='code',
            field=models.CharField(max_length=6, verbose_name=b'Code'),
        ),
        migrations.AlterField(
            model_name='eventforbusstop',
            name='halfHourPeriod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.HalfHourPeriod', verbose_name=b'Half Hour Period'),
        ),
        migrations.AlterField(
            model_name='eventforbusstop',
            name='timePeriod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.TimePeriod', verbose_name=b'Time Period'),
        ),
        migrations.AlterField(
            model_name='eventforbusstop',
            name='zonification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.ZonificationTransantiago', verbose_name=b'zonification'),
        ),
        migrations.AlterField(
            model_name='eventforbusv2',
            name='halfHourPeriod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.HalfHourPeriod', verbose_name=b'Half Hour Period'),
        ),
        migrations.AlterField(
            model_name='eventforbusv2',
            name='timePeriod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.TimePeriod', verbose_name=b'Time Period'),
        ),
        migrations.AlterField(
            model_name='eventforbusv2',
            name='zonification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.ZonificationTransantiago', verbose_name=b'zonification'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='stopCode',
            field=models.CharField(max_length=6, null=True, verbose_name=b'StopCode'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='zonification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AndroidRequests.ZonificationTransantiago', verbose_name=b'zonification'),
        ),
        migrations.AlterField(
            model_name='servicesbybusstop',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name=b'Token'),
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together=set(['code', 'gtfs']),
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='id',
        ),
    ]
    """
